version: "3.11"

services:
  db:
      image: postgres:13-alpine
      volumes:
        - dev-db-data:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=eltechdb
        - POSTGRES_USER=eltechuser
        - POSTGRES_PASSWORD=eltechpassword
      ports:
        - "5432:5432"
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./eltech:/eltech
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=eltechdb
      - DB_USER=eltechuser
      - DB_PASS=eltechpassword
      - DEBUG=1
      - DB_PORT=5432
    depends_on:
      - db

volumes:
  dev-db-data:
  dev-static-data: