# Generated by Django 4.2.7 on 2023-11-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_weeklydeal_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklydeal',
            name='deal_time',
            field=models.DateField(null=True),
        ),
    ]
