# Generated by Django 4.2.7 on 2023-11-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
