# Generated by Django 4.2.7 on 2023-11-22 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_created_at'),
        ('core', '0023_alter_order_order_note'),
    ]

    operations = [
    ]
