# Generated by Django 4.2.7 on 2023-11-22 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_merge_20231122_1752'),
        ('core', '0024_merge_20231122_1836'),
    ]

    operations = [
    ]
