# Generated by Django 4.2.7 on 2023-11-23 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_merge_20231122_1859'),
        ('core', '0025_product_is_deleted'),
    ]

    operations = [
    ]
