# Generated by Django 4.2.7 on 2023-11-24 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_merge_20231123_0941'),
        ('core', '0026_productnotification'),
    ]

    operations = [
    ]
